class InfinityFormerConfig:
    def __init__(self,
                 vocab_size=50265,
                 hidden_size=768,
                 num_hidden_layers=12,
                 num_attention_heads=12,
                 intermediate_size=3072,
                 hidden_act="gelu",
                 hidden_dropout_prob=0.1,
                 attention_probs_dropout_prob=0.1,
                 max_position_embeddings=512,
                 type_vocab_size=2,
                 initializer_range=0.02,
                 layer_norm_eps=1e-5,
                 pad_token_id=1,
                 bos_token_id=0,
                 eos_token_id=2,
                 use_cache=True,
                 use_return_dict=True,
                 output_attentions=False,
                 output_hidden_states=False,
                 memory_compression_ratio=0.5,
                 memory_compression_frequency=10,
                 kernel_type='elu',
                 kernel_epsilon=1e-6):
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.hidden_act = hidden_act
        self.intermediate_size = intermediate_size
        self.hidden_dropout_prob = hidden_dropout_prob
        self.attention_probs_dropout_prob = attention_probs_dropout_prob
        self.max_position_embeddings = max_position_embeddings
        self.type_vocab_size = type_vocab_size
        self.initializer_range = initializer_range
        self.layer_norm_eps = layer_norm_eps
        self.pad_token_id = pad_token_id
        self.bos_token_id = bos_token_id
        self.eos_token_id = eos_token_id
        self.use_cache = use_cache
        self.use_return_dict = use_return_dict
        self.output_attentions = output_attentions
        self.output_hidden_states = output_hidden_states
        self.memory_compression_ratio = memory_compression_ratio
        self.memory_compression_frequency = memory_compression_frequency
        self.kernel_type = kernel_type
        self.kernel_epsilon = kernel_epsilon
